### ISSUE TITLE
Power operation throws `ComputeResourcesVm not found` 

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#10]
When trying to `Power On` a VM, it redirects to this error
![screenshot from 2019-01-03 17-30-40](https://user-images.githubusercontent.com/6758282/50636779-6321d100-0f7d-11e9-9015-73d2595a32da.png)

**Comment by masayag** [comment]
@vatsalparekh could you re-test this issue and open if re-occur ?

**Comment by vatsalparekh** [comment]
@masayag still seeing this with `Power On`, please reopen this

**Comment by masayag** [comment]
Fixed by https://github.com/fog/fog-kubevirt/pull/104, required fog-kubevirt-1.2.0 to verify.

**Comment by masayag** [comment]
Requires also https://github.com/masayag/foreman_kubevirt/pull/64

**Comment by vatsalparekh** [comment]
Seems working now
