### ISSUE TITLE
Adding compute resource should have separate port option

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#11]
Adding a new compute profile currently expects `IP+Port` in hostname, which makes it confusing, having a separate input option for port would be a better UX

**Comment by masayag** [comment]
Fixed by commit a8a5f7cd09d9fdae82cb7f7e48c2e3b3a91df990, the hostname field is split to two fields, server and port:

![selection_999 001](https://user-images.githubusercontent.com/316242/51806132-c6520b00-227e-11e9-9422-80bf1b8fdf40.png)
