### ISSUE TITLE
Test connection pass even though the Namespace doesn't exist

### ISSUE THREAD

**Issue by shiramax** [masayag/foreman_kubevirt#24]
When creating a compute resource, the test connection pass even though the namespace that inserted doesn't exist.

**Comment by masayag** [comment]
A validation was added t o fog-kubevirt, if there is no such namespace, the error below will be shown when running `test_connection`
![Selection_999(236)](https://user-images.githubusercontent.com/316242/55512816-bda9f680-566c-11e9-867e-c5c44a7a22bc.png)

https://github.com/fog/fog-kubevirt/pull/92

**Comment by masayag** [comment]
Fixed by fog/fog-kubevirt#92
