### ISSUE TITLE
Set a proper HTTP link for the about page

### ISSUE THREAD

**Issue by ananace** [masayag/foreman_kubevirt#26]
As the plugin currently has a home - here - along with an issue tracker, perhaps it'd be a good idea to set the link on the about page to point here instead of to `http://todo` :slightly_smiling_face:

**Comment by masayag** [comment]
@ananace thanks for reporting the issue. I've uploaded a patch for that.
We'd expect another PR for changing the path once this plugin will get accepted to the Foreman organization.
