### ISSUE TITLE
Storage improvements

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#28]
Currently I see that when creating a new host the storage option are shown, but below are confusions around using it.
-If someone was to create a new claim, user would want to do it with `CDI` or `DataVolume`, those options are missing
And in that case, user won't need to select `PersistantVolume` but rather a `StorageClass` type because PV and PVC would be controller by Storage controller in most cases, except ones like local-storage.
- If user wants to create a Blank disk, just `storageclass` should be required with `Create New Claim` (except the cases where there's no dynamic provisioner)
- If someone selects a PVC directly, there's no need to select the PV after that, so that option is useless and misleading
- In the list of PVC, more details about Storageclass and PVC details should be much better

**Comment by masayag** [comment]
Fixed by https://github.com/masayag/foreman_kubevirt/pull/43

If wishes to have specific storage other than dynamic provisioning via storage class, please report an issue for each method.
