### ISSUE TITLE
no validation when adding compute resource through API

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#34]
Trying the example from #18 with wrong token worked, which should actually have shown error and failed
![screenshot from 2019-02-26 15-54-57](https://user-images.githubusercontent.com/6758282/53406008-112a8400-39df-11e9-9e11-52d69c6bc040.png)

**Comment by masayag** [comment]
Fixed by https://github.com/masayag/foreman_kubevirt/pull/39
