### ISSUE TITLE
no validation on compute resource 

### ISSUE THREAD

**Issue by vatsalparekh** [masayag/foreman_kubevirt#5]
![foreman](https://user-images.githubusercontent.com/6758282/49573253-9a439900-f963-11e8-891d-98562a2e6fdf.gif)

**Comment by masayag** [comment]
Fixed by commit a8a5f7cd09d9fdae82cb7f7e48c2e3b3a91df990:

![selection_999 002](https://user-images.githubusercontent.com/316242/51806159-1761ff00-227f-11e9-885b-951a58b5d2bd.png)

Please report additional validation issues individually.
